name: SDK Upload
description: Upload a directory to the Ably SDK Team S3 bucket.
author: Ably
branding:
  icon: upload-cloud
  color: orange
runs:
  using: node16
  main: dist/index.js
inputs:
  sourcePath:
    description: Path to a directory containing the files to upload, relative to the root directory of the repository.
    required: true
  githubToken:
    description: This should be a token with access to the repository scoped in as a secret. This will be available in the GitHub runner environment by default as `secrets.GITHUB_TOKEN`.
    required: true
  artifactName:
    description: |
      The name of the artifact to be uploaded, for example `docs`.
      If supplied then it is used as the directory name within S3 for the uploaded artifacts, as well as within the GitHub deployment environment name.
      If not supplied or supplied as an empty string then the artifacts are uploaded to S3 at root for this deployment context.
    required: false
    default: ''
  mode:
    description: |
      Specify `"preempt"` in order use this action before content build in order to output the URL base.
    required: false
outputs:
  url-base:
    description: |
      The URL base. For example:

          https://sdk.ably.com/builds/ably/ably-flutter/pull/307/dartdoc/

      When used in the Flutter SDK repository, with `artifactName` as `"dartdoc"`.
