name: SDK Upload
description: Upload a directory to the Ably SDK Team S3 bucket.
author: Ably
branding:
  icon: upload-cloud
  color: orange
runs:
  using: node16
  main: dist/index.js
inputs:
  s3AccessKeyId:
    description: AWS IAM user's access key id.
    required: true
  s3AccessKey:
    description: AWS IAM user's secret access key.
    required: true
  sourcePath:
    description: Path to a directory containing the files to upload, relative to the root directory of the repository.
    required: true
  githubToken:
    description: This should be a token with access to the repository scoped in as a secret. This will be available in the GitHub runner environment by default as `secrets.GITHUB_TOKEN`.
    required: true
  artifactName:
    description: The name of the artifact to be uploaded, for example `docs`. This will be used as the directory name within S3 for uploaded artifacts.
    required: true
