on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # Test that this action works with AWS credentials provided by the
  # aws-actions/configure-aws-credentials action using GitHub OIDC.
  #
  # See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect
  test-oidc:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::884096606738:role/ably-sdk-builds-sdk-upload-action
          role-session-name: "${{ github.run_id }}-${{ github.run_number }}"
      - uses: actions/checkout@v2
      - name: Create test files for upload
        run: |
          mkdir -p test
          echo "success!" > test/build-output.txt
      - name: Test action invocation works
        uses: ./
        with:
          sourcePath: test
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactName: test
